language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover tests
env:
  global:
    - DISABLE_LOGGING=true
