language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: unit-test
      script: python -m unittest discover tests
    - stage: integration-test
      script: echo "Integration test goes here!"
      python: "2.7"
env:
  global:
    - DISABLE_LOGGING=true
